/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Frame;
import javax.swing.JFrame;
import sun.awt.resources.awt;

/**
 *
 * @author mariana
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Inserir
     */
    public Menu() {
        initComponents();
        this.setVisible(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }
    
    private void mnSairActionPerformed(java.awt.event.ActionEvent evt){
        this.dispose();
    }
    
    private void mnInserirActionPerformed(java.awt.event.ActionEvent evt) {
        Inserir inserir = new Inserir();
        pnl_menu.removeAll();
        pnl_menu.add(inserir);
        pnl_menu.updateUI();
    }

    private void mnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {
        Visualizar visualizar = new Visualizar();
        pnl_menu.removeAll();
        pnl_menu.add(visualizar);
        pnl_menu.updateUI();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_menu = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        mnVisualizar = new javax.swing.JMenuItem();
        mnInserir = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnl_menuLayout = new javax.swing.GroupLayout(pnl_menu);
        pnl_menu.setLayout(pnl_menuLayout);
        pnl_menuLayout.setHorizontalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnl_menuLayout.setVerticalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menu.setText("Menu");

        mnVisualizar.setText("Vizualizar");
        menu.add(mnVisualizar);

        mnInserir.setText("Inserir");
        menu.add(mnInserir);

        jMenuBar1.add(menu);

        sair.setText("Sair");

        mnSair.setText("Sair");
        sair.add(mnSair);

        jMenuBar1.add(sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem mnInserir;
    private javax.swing.JMenuItem mnSair;
    private javax.swing.JMenuItem mnVisualizar;
    private javax.swing.JPanel pnl_menu;
    private javax.swing.JMenu sair;
    // End of variables declaration//GEN-END:variables
}
